name: "Install x86_64 Dependencies on Linux"
description: "Install dependencies for x86_64 native compilation and testing"

runs:
  using: "composite"
  steps:
    - name: Setup ubuntu
      shell: bash
      run: sysctl vm.mmap_rnd_bits=28

    - name: Install dependencies
      shell: bash
      run: |
        apt-get update -y -qq
        apt-get install -y --no-install-recommends \
        build-essential ca-certificates cmake git jq clang llvm llvm-18-tools libclang-rt-18-dev clang-tidy \
        python-is-python3 gcovr ninja-build wget \
        python3-dev python3-venv python3 python3-pip \
        gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

    - name: Install binaryen
      shell: bash
      run: |
        wget https://github.com/WebAssembly/binaryen/releases/download/version_122/binaryen-version_122-x86_64-linux.tar.gz
        tar -xzf binaryen-version_122-x86_64-linux.tar.gz
        echo "$PWD/binaryen-version_122/bin" >> $GITHUB_PATH

    - name: Install Googletest
      shell: bash
      run: |
        git clone --depth 1 --branch release-1.11.0 https://github.com/google/googletest.git \
        && cd googletest && mkdir build && cd build && cmake .. && make -j $(nproc) && make install

    - name: Install wabt
      shell: bash
      run: |
        wget https://github.com/WebAssembly/wabt/releases/download/1.0.36/wabt-1.0.36-ubuntu-20.04.tar.gz
        tar -xzf wabt-1.0.36-ubuntu-20.04.tar.gz
        echo "$PWD/wabt-1.0.36/bin" >> $GITHUB_PATH

    - name: Install bazel
      shell: bash
      run: |
        wget https://github.com/bazelbuild/bazel/releases/download/7.0.0/bazel-7.0.0-linux-x86_64
        mv bazel-7.0.0-linux-x86_64 /usr/local/bin/bazel
        chmod 777 /usr/local/bin/bazel
