name: "Install ARM64 Dependencies on Linux"
description: "Install dependencies for ARM64 native compilation and testing"

runs:
  using: "composite"
  steps:
    - name: Setup ubuntu
      shell: bash
      run: sysctl vm.mmap_rnd_bits=28

    - name: Install dependencies
      shell: bash
      run: |
        apt-get update -y -qq
        apt-get install -y --no-install-recommends \
        build-essential ca-certificates cmake git jq clang llvm llvm-18-tools libclang-rt-18-dev clang-tidy \
        python-is-python3 gcovr wget python3-dev python3-venv python3 python3-pip

    - name: Install binaryen
      shell: bash
      run: |
        wget https://github.com/WebAssembly/binaryen/releases/download/version_122/binaryen-version_122-aarch64-linux.tar.gz
        tar -xzf binaryen-version_122-aarch64-linux.tar.gz
        echo "$PWD/binaryen-version_122/bin" >> $GITHUB_PATH

    - name: Install Googletest
      shell: bash
      run: |
        git clone --depth 1 --branch release-1.11.0 https://github.com/google/googletest.git \
        && cd googletest && mkdir build && cd build && cmake .. && make -j $(nproc) && make install

    - name: Install wabt
      shell: bash
      run: |
        wget https://github.com/Schleifner/wabt/releases/download/release-1.0.36/wabt-85283774695bde90033d33e98a810f8448d53964-ubuntu-24.04-arm.tar.gz
        tar -xzf wabt-85283774695bde90033d33e98a810f8448d53964-ubuntu-24.04-arm.tar.gz
        echo "$PWD/wabt-85283774695bde90033d33e98a810f8448d53964/bin" >> $GITHUB_PATH
