name: "fuzz-qemu"
description: "run fuzz for tricore"
inputs:
  timeout:
    description: "fuzz timeout in second"
    required: true
  cmake_flags:
    description: "additional cmake flags"
    required: false
  cpp_flags:
    description: "additional c++ flags"
    required: false
outputs:
  log_file:
    description: "fuzz log"
    value: ${{ steps.set-output.outputs.log_file }}

runs:
  using: "composite"
  steps:
    - shell: bash
      id: set-output
      run: echo "log_file=$(pwd)/build_fuzz/log" >> $GITHUB_OUTPUT
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - shell: bash
      run: |
        cmake -B build_fuzz -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=/usr/bin/tricore-elf-gcc -DCMAKE_CXX_COMPILER=/usr/bin/tricore-elf-g++ -DVB_ENABLE_DEV_FEATURE=OFF -DENABLE_FUZZ=1 -DFUZZ_ONLY_WITH_DEBUGGER=1 ${{ inputs.cmake_flags }} -DCMAKE_CXX_FLAGS="${{ inputs.cpp_flags }}"
        cmake --build build_fuzz --target vb_debugger_fuzz --parallel
    - shell: bash
      run: |
        mkdir -p /dev/shm/wasm-fuzz
    - shell: bash
      run: node .github/scripts/run_qemu_fuzz.cjs
      env:
        TIMEOUT: ${{ inputs.timeout }}
        VB_FUZZ_TARGET_DIR: /dev/shm/wasm-fuzz

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: fuzz_failed_modules-${{ github.run_id }}
        path: /dev/shm/wasm-fuzz
